WITH JOINED_2021_USERS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), 
TOTAL_USERS AS (
    SELECT COUNT(*) AS TOTAL
    FROM JOINED_2021_USERS
)
SELECT 
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT TOTAL FROM TOTAL_USERS), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN JOINED_2021_USERS U
  ON O.USER_ID = U.USER_ID
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;
